/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
get_ticket_1(client_data *argp, client_data *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, get_ticket,
		(xdrproc_t) xdr_client_data, (caddr_t) argp,
		(xdrproc_t) xdr_client_data, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_service_1(client_data *argp, service_data *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, get_service,
		(xdrproc_t) xdr_client_data, (caddr_t) argp,
		(xdrproc_t) xdr_service_data, (caddr_t) clnt_res,
		TIMEOUT));
}
