/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

#include <unistd.h>

void bakery_prog_1(char *host)
{
	CLIENT *clnt;

    client_data cdata;
	service_data sdata;

	enum clnt_stat retval_1;
	enum clnt_stat retval_2;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    cdata.pid = getpid();

    printf("Client (pid: %d) is going to get ticket.\n", cdata.pid);

	retval_1 = get_ticket_1(&cdata, NULL, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

    printf("Client (pid: %d) got ticket %d and is going to get service.\n", cdata.pid, cdata.ticket_number);

	retval_2 = get_service_1(&cdata, &sdata, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

    printf("Client (pid: %d) got service:\n\
- Served by pid: %d\n\
- Served by tid: %d\n\
- Service time: %ld ms\n\
- Bun: %s", cdata.pid, sdata.served_by_pid, sdata.served_by_tid, sdata.service_time_ms, sdata.bun_name);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc > 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = (argc == 2) ? argv[1] : "localhost";
	bakery_prog_1 (host);
exit (0);
}
