/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct client_data {
	int pid;
	int ticket_number;
};
typedef struct client_data client_data;

struct service_data {
	int served_by_pid;
	int served_by_tid;
	char bun_name[255];
	quad_t service_time_ms;
};
typedef struct service_data service_data;

#define BAKERY_PROG 0x21234567
#define BAKERY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_ticket 1
extern  enum clnt_stat get_ticket_1(client_data *, void *, CLIENT *);
extern  bool_t get_ticket_1_svc(client_data *, void *, struct svc_req *);
#define get_service 2
extern  enum clnt_stat get_service_1(client_data *, service_data *, CLIENT *);
extern  bool_t get_service_1_svc(client_data *, service_data *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_ticket 1
extern  enum clnt_stat get_ticket_1();
extern  bool_t get_ticket_1_svc();
#define get_service 2
extern  enum clnt_stat get_service_1();
extern  bool_t get_service_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_client_data (XDR *, client_data*);
extern  bool_t xdr_service_data (XDR *, service_data*);

#else /* K&R C */
extern bool_t xdr_client_data ();
extern bool_t xdr_service_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
