/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

#include <unistd.h>

void bakery_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	client_data client_data_out;
	client_data client_data_in;
	enum clnt_stat retval_2;
	service_data service_data_out;
    service_data_out.served_by_tid = 0;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    client_data_in.pid = getpid();
    client_data_in.ticket_number = -10;

    printf("pid: %d\n", getpid());

	retval_1 = get_ticket_1(&client_data_in, &client_data_out, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror(clnt, "call failed");
	} else {
        client_data_in = client_data_out;
    }

    printf("Client with pid %d got ticket %d\n", client_data_in.pid, client_data_in.ticket_number + 1);

	/* retval_2 = get_service_1(&client_data_in, &service_data_out, clnt); */
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror(clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

    /* while (service_data_out.served_by_tid == 0) {}; */

    /* sleep(1); */

    printf("Client with pid %d and ticket %d got served:\n"
        "- served by pid: %d\n"
        "- served by tid: %d\n"
        /* "- service time: %ld\n" */
        "- got bun: %s\n", client_data_in.pid, client_data_in.ticket_number + 1,
        service_data_out.served_by_pid, service_data_out.served_by_tid,
        /* service_data_out.service_time_ms, */
        service_data_out.bun_name);
}


int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
        host = "localhost";
	} else if (argc == 2) {
        host = argv[1];
    } else {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
    }

	bakery_prog_1(host);
    exit(0);
}
